# Generated by Django 2.2.3 on 2019-09-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetText', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('userDescription', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('userFollowersCount', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('userFriendsCount', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('inReplytoUserID', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('userLocation', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('retweetCount', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('tweetLanguage', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('tweetedBy', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('originalTweetUserID', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('originalTweetFriendsCount', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('originalTweetFollowersCount', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('originalTweetRTCount', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('retweetedUser', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
