# Generated by Django 2.2.3 on 2019-09-23 17:13

import dataAnalysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0002_graphimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphimage',
            name='imageURL',
        ),
        migrations.AlterField(
            model_name='graphimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dataAnalysis.models.user_directory_path),
        ),
    ]
